### ISSUE TITLE
Quadtree Demo has off-by-one error

### ISSUE THREAD

**Issue by zauberparacelsus** [prajogotio/prajogotio.github.io#1]
The Quad-Tree demo has an off-by-one error, that prevents the smallest nodes along the left and top edges from being filled in.

![quadtreeterraindemobug](https://cloud.githubusercontent.com/assets/548168/14095491/f205ee04-f52e-11e5-882f-512dfa2fb810.png)

**Comment by prajogotio** [comment]
@zauberparacelsus Thank you for noticing the bug and opening up an issue. I have committed a fix to that, and also improved the interaction a little bit so hopefully it can be more useable as a demo :)

**Comment by zauberparacelsus** [comment]
Aye, yw :-)
